# Generated by Django 6.0.1 on 2026-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("author", models.TextField()),
                ("price", models.FloatField()),
                ("title", models.TextField()),
                ("synopsis", models.TextField()),
            ],
        ),
    ]
