# Generated by Django 6.0.1 on 2026-01-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstdjango", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyModel",
            new_name="Book",
        ),
    ]
