# Generated by Django 6.0.1 on 2026-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstdjango", "0002_rename_mymodel_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.TextField(default="Classic"),
        ),
    ]
